/** Archivos reales en `public/skills/utility/`. El slug del catálogo apunta al nombre del fichero. */
export const UTILITY_SKILL_FILES: Record<string, string> = {
  "acute-ears": "ACUTE-EARS.webp",
  aiming: "AIMING.webp",
  alchemy: "ALCHEMY.webp",
  ambush: "AMBUSH.webp",
  "animal-handling": "ANIMAL-HANDLING.webp",
  arcane: "ARCANE.webp",
  "attack-of-opportunity": "ATTACK-OF-OPPORTUNITY.webp",
  backfire: "BACKFIRE.webp",
  balance: "BALANCE.webp",
  "basic-science": "BASIC-SCIENCE.webp",
  calligraphy: "CALLIGRAPHY.webp",
  cartography: "CARTOGRAPHY.webp",
  "cat-like-reflexes": "CAT-LIKE REFLEXES.webp",
  catcher: "CATCHER.webp",
  "cesta-punta": "CESTA PUNTA.webp",
  "character-actor": "CHARACTER ACTOR.webp",
  "chopper-pilot": "CHOPPER PILOT.webp",
  climbing: "CLIMBING.webp",
  cockroach: "COCKROACH.webp",
  cooking: "COOKING.webp",
  deception: "DECEPTION.webp",
  "detect-lies": "DETECT LIES.webp",
  "detect-trap": "DETECT TRAP.webp",
  "determine-value": "DETERMINE VALUE.webp",
  diplomacy: "DIPLOMACY.webp",
  dodge: "DODGE.webp",
  "double-tap": "DOUBLE TAP.webp",
  driving: "DRIVING.webp",
  "dumpster-diving": "DUMPSTER DIVING.webp",
  endurance: "ENDURANCE.webp",
  engineering: "ENGINEERING.webp",
  "escape-artist": "ESCAPE ARTIST.webp",
  "escape-plan": "ESCAPE PLAN.webp",
  "explosives-handling": "EXPLOSIVES HANDLING.webp",
  fabricate: "FABRICATE.webp",
  "find-crawler": "FIND CRAWLER.webp",
  "find-trap": "FIND TRAP.webp",
  "gear-head": "GEAR HEAD.webp",
  "good-first-impression": "GOOD FIRST IMPRESSION.webp",
  "hide-in-shadows": "HIDE IN SHADOWS.webp",
  "improvised-explosive-device": "IMPROVISED EXPLOSIVE DEVICE.webp",
  "incendiary-device-handling": "INCENDIARY DEVICE HANDLING.webp",
  infusion: "INFUSION.webp",
  intimidate: "INTIMIDATE.webp",
  investigation: "INVESTIGATION.webp",
  "iron-stomach": "IRON STOMACH.webp",
  jumping: "JUMPING.webp",
  leadership: "LEADERSHIP.webp",
  "light-on-your-feet": "LIGHT ON YOUR FEET.webp",
  lockpicking: "LOCKPICKING.webp",
  lore: "LORE.webp",
  negotiation: "NEGOTIATION.webp",
  pathfinder: "PATHFINDER.webp",
  perception: "PERCEPTION.webp",
  performance: "PERFORMANCE.webp",
  persuasion: "PERSUASION.webp",
  regeneration: "REGENERATION.webp",
  religion: "RELIGION.webp",
  repair: "REPAIR.webp",
  riding: "RIDING.webp",
  ropework: "ROPEWORK.webp",
  running: "RUNNING.webp",
  salvage: "SALVAGE.webp",
  scutelliphily: "SCUTELLIPHILY.webp",
  "shield-block": "SHIELD BLOCK.webp",
  "sleight-of-hand": "SLEIGHT OF HAND.webp",
  smithing: "SMITHING.webp",
  stealth: "STEALTH.webp",
  streetwise: "STREETWISE.webp",
  survival: "SURVIVAL.webp",
  swimming: "SWIMMING.webp",
  tactics: "TACTICS.webp",
  "tattoo-artistry": "TATTOO ARTISTRY.webp",
  taunt: "TAUNT.webp",
  throwing: "THROWING.webp",
  tracking: "TRACKING.webp",
  "trap-engineer": "TRAP ENGINEER.webp",
  "zone-of-control": "ZONE OF CONTROL.webp",
};

export function utilitySkillArtUrl(slug: string): string | null {
  const file = UTILITY_SKILL_FILES[slug];
  if (!file) return null;
  return `/skills/utility/${encodeURIComponent(file)}`;
}
